apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: worker-node-2
  name: pro-api-server
  namespace: anoop
spec:
  containers:
  - image: anoop4686/nginx-webserver-webserver:v1
    name: api-server-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
