apiVersion: v1
kind: Service
metadata:
  name: samsung-prod
  namespace: samsung-prod
spec: 
  type: NodePort
  selector:
    env:  prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
