apiVersion: v1
kind: Service
metadata:
  name: anoop-prod
  namespace: anoop-prod
spec:
  type: NodePort
  selector:
    env:  prod
  ports:
    - protocol: TCP
      port: 8585
      targetPort: 8585
      nodePort: 31500
