apiVersion: v1
kind: Service
metadata:
  name: samsung-uat
  namespace: samsung-uat
spec: 
  type: NodePort
  selector:
    env:  uat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
