apiVersion: v1
kind: Service
metadata:
  name: samsung-prod
  namespace: samsung-prod
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
