apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app

  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: anoop4686/images:web_host_version1
        ports:
        - containerPort: 80
