apiVersion: apps/v1
kind: Deployment
metadata:
  name: web_app
  labels:
    app: web_app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: web_app

  template:
    metadata:
      labels:
        app: web_app
    spec:
      containers:
      - name: web_app
        image: anoop4686/images:web_host_version1
        ports:
        - containerPort: 80
