apiVersion: v1
kind: Pod
metadata:
  name: nightclub
  namespace: anoop-uat
  labels:
    env: prod
spec:
  nodeName: worker-node-2
  volumes:
   - name: backup-files
     hostPath:
      path: /opt/backup-files
      type: Directory
  containers:
   - name: nightclub
     image: anoop4686/cent-os-night-club-8585:v1
     volumeMounts:
      - name: backup-files
        mountPath: /var/www/html/
        readOnly:  true
